### #1 import the numpy package under the name np

In [2]:
import numpy as np

### #2 print the numpy version and configuration

In [4]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/owner/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\

### #3 create null vector of size 10

In [7]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### #4 how to find the memory size of any array

In [10]:
v.itemsize * v.size

80

### #6 create a null vector of size 10 but the fifth value which is 1

In [15]:
v5 = np.zeros(10)
v5[4] = 1
print(v5)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### #7 create a vector with values ranging from 10 to 49 

In [17]:
v7 = np.arange(10, 50)
print(v7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### #8 reverse a vector

In [19]:
v8 = v7[::-1]
print(v8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### #9 create a 3*3 matirix with values ranging from 0 to 8

In [23]:
v9 = np.arange(0, 9).reshape(3, 3)
v9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### #10 find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
v10 = np.nonzero([1, 2, 0, 0, 4, 0])
print(v10)

(array([0, 1, 4], dtype=int64),)


### #11 create a 3*3 identity matrix

In [26]:
v11 = np.eye(3)
print(v11)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### #12 create a 3*3*3 array with random values

In [29]:
v12 = np.random.random((3, 3, 3))
print(v12)

[[[ 0.3317697   0.4019865   0.98723049]
  [ 0.14985019  0.69719616  0.95885865]
  [ 0.14886914  0.26995204  0.18896853]]

 [[ 0.7929844   0.16684984  0.95035978]
  [ 0.72043594  0.75072476  0.45903114]
  [ 0.67119827  0.56349312  0.36118625]]

 [[ 0.09816024  0.94140217  0.06920714]
  [ 0.00638497  0.00291704  0.39376799]
  [ 0.48967929  0.23062569  0.11827586]]]


### #13 create a 10*10 array with random values and find the minimum and maximum values

In [33]:
v13 = np.random.random((10, 10))
v_min, v_max = v13.min(), v13.max()
print(v13)
print("minimum: {}\nmaximum: {}".format(v_min, v_max))

[[  4.46255692e-01   2.87972730e-01   5.87857870e-02   2.57962429e-01
    1.83624924e-01   8.18425886e-01   2.49435121e-01   8.68612721e-01
    7.71824581e-02   8.24909833e-01]
 [  4.00678437e-01   3.73243779e-04   6.41220483e-01   1.80396824e-01
    3.09260217e-01   4.61858312e-01   1.47766318e-01   5.09824728e-01
    6.92270098e-01   4.91667949e-01]
 [  4.87976862e-01   3.53576364e-01   4.11579074e-01   5.99931492e-01
    2.65994265e-01   8.06848650e-01   7.98198873e-01   1.86530998e-01
    2.26413721e-01   5.43704756e-03]
 [  8.85221326e-01   1.24906478e-01   1.53037694e-01   4.06992446e-01
    6.80639809e-01   4.04219433e-01   8.90303239e-02   5.40978842e-01
    8.74984539e-02   5.61638050e-01]
 [  8.26170097e-01   7.72814757e-01   5.12495240e-01   1.69676588e-01
    2.41417664e-03   2.89262996e-02   9.60378111e-02   9.14509103e-01
    1.46313712e-02   3.19092409e-01]
 [  4.17934246e-02   5.33359984e-01   4.40281310e-01   2.50517641e-01
    1.72840590e-01   3.71293365e-01   5.97125

### #14 create a random vector of size 30 and find the mean value

In [35]:
v14 = np.random.random(30)
m = v14.mean()
print(v14, "\nmean: {}".format(m))

[ 0.09775099  0.34446149  0.73407888  0.04826838  0.38545114  0.90722416
  0.76380958  0.28729252  0.47131646  0.2344518   0.34331189  0.19116147
  0.23269645  0.00196597  0.74304705  0.3477553   0.18955628  0.14547615
  0.98955573  0.7259419   0.54811116  0.10617323  0.20805283  0.88948844
  0.2681921   0.79805622  0.92959251  0.03792316  0.50794581  0.03422138] 
mean: 0.4170776810440073


### #15 create a 2D array with 1 on the border and 0 inside

In [43]:
v15 = np.ones((10, 10))
v15[1:-1, 1:-1] = 0
print(v15)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### #16 how to add a border (filled with 0's) around an existing array ?

In [49]:
v16 = np.ones((5, 5))
v16 = np.pad(v16, pad_width=1, mode='constant', constant_values=0)
print(v16)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### #17 what is the result of the following expression ?

In [53]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### #18 create a 5 * 5 matrix with values 1,2,3,4 just below the diagonal

In [61]:
v18 = np.diag(1+np.arange(4), k=-1)
print(v18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### #19 create a 8 * 8 matrix and fill it with a checkerboard pattern

In [72]:
v19 = np.zeros((8, 8))
v19[1::2, ::2] = 1
v19[::2, 1::2] = 1
print(v19)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


### #20 consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ? 

In [75]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### #21 create a chekerboard 8 * 8 matrix using the tile function

In [80]:
v21 = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(v21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### #22 normalize a 5 * 5 random matrix

In [85]:
v22 = np.random.random((5, 5))
v_min, v_max = v22.min(), v22.max()
v22 = (v22 - v_min) / (v_max - v_min)
print(v22)

[[ 0.54798513  0.72175737  0.66905055  0.84902191  0.06935279]
 [ 0.66691974  0.39419046  0.13803938  0.83844753  0.78277533]
 [ 0.11521145  0.43479375  0.02826264  0.86018886  0.27289744]
 [ 0.          0.26959778  0.30721538  0.93058412  0.52731962]
 [ 0.86047152  0.65245503  0.03413671  1.          0.10012704]]


In [88]:
v22 = np.random.random((5, 5))
v_mean, v_sigma = v22.mean(), v22.std()
v22 = (v22 - v_mean) / v_sigma
print(v22)

[[-0.57910368  0.57952123 -0.53841693  0.39794418  1.23909612]
 [ 1.02355206  0.07015935 -0.9335643  -1.64054507 -1.15248475]
 [ 0.23306714  0.62096672  0.56096232  1.32393503 -1.65334587]
 [-1.20482773 -1.64393358 -1.01696989  0.40664202  1.54735916]
 [-0.07189456  0.83571432  1.14276629  1.03297972 -0.57957929]]


### #23 create a custom dtype that describes a color as four unsinged bytes 

In [91]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### #24 multiply a 5 * 3 matrix by a 3 * 2 matrix (real matrix product)

In [97]:
v24 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
v24 = np.ones((5, 3)) @ np.ones((3, 2))
print(v24)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### #25 given a 1D array, negate all elements which are between 3 and 8, in place

In [101]:
v25 = np.arange(10)
v25[(3 <= v25) & (v25 <= 8)] *= -1
print(v25)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]
