### #1 import the numpy package under the name np

In [1]:
import numpy as np

### #2 print the numpy version and configuration

In [2]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/owner/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\

### #3 create null vector of size 10

In [3]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### #4 how to find the memory size of any array

In [4]:
v.itemsize * v.size

80

### #6 create a null vector of size 10 but the fifth value which is 1

In [5]:
v5 = np.zeros(10)
v5[4] = 1
print(v5)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### #7 create a vector with values ranging from 10 to 49 

In [6]:
v7 = np.arange(10, 50)
print(v7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### #8 reverse a vector

In [7]:
v8 = v7[::-1]
print(v8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### #9 create a 3*3 matirix with values ranging from 0 to 8

In [8]:
v9 = np.arange(0, 9).reshape(3, 3)
v9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### #10 find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
v10 = np.nonzero([1, 2, 0, 0, 4, 0])
print(v10)

(array([0, 1, 4], dtype=int64),)


### #11 create a 3*3 identity matrix

In [10]:
v11 = np.eye(3)
print(v11)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### #12 create a 3*3*3 array with random values

In [11]:
v12 = np.random.random((3, 3, 3))
print(v12)

[[[ 0.16553517  0.9170792   0.6802623 ]
  [ 0.59412448  0.47422429  0.72147801]
  [ 0.83990066  0.29417284  0.00267399]]

 [[ 0.13364429  0.43818334  0.55015465]
  [ 0.82923907  0.00693051  0.77094044]
  [ 0.31369573  0.38614678  0.12889479]]

 [[ 0.27379147  0.24096598  0.30755517]
  [ 0.15609902  0.0571157   0.34427864]
  [ 0.86325675  0.88018281  0.90873092]]]


### #13 create a 10*10 array with random values and find the minimum and maximum values

In [12]:
v13 = np.random.random((10, 10))
v_min, v_max = v13.min(), v13.max()
print(v13)
print("minimum: {}\nmaximum: {}".format(v_min, v_max))

[[ 0.150043    0.60316657  0.63610336  0.33349458  0.76444749  0.86277742
   0.83733694  0.64731613  0.69394359  0.22244952]
 [ 0.17822353  0.5469356   0.27344761  0.64973111  0.06006025  0.75359459
   0.70238014  0.83676037  0.78847466  0.08441831]
 [ 0.05023547  0.02293747  0.65882755  0.20680162  0.18776867  0.38304141
   0.47459191  0.66422375  0.24865429  0.69134233]
 [ 0.17430299  0.72489995  0.18639755  0.83114605  0.58611833  0.03967815
   0.48507829  0.52259638  0.4729302   0.15175323]
 [ 0.03172841  0.88887217  0.98645862  0.06870123  0.7485692   0.68036888
   0.05907348  0.64087283  0.28984593  0.76055572]
 [ 0.32479306  0.71457579  0.03595595  0.76247454  0.65401346  0.41241718
   0.67524871  0.3840511   0.09681849  0.05516349]
 [ 0.7202785   0.9207773   0.27879485  0.07762563  0.1777103   0.01517417
   0.14891039  0.7600344   0.21478011  0.08383524]
 [ 0.41273115  0.35527733  0.45874798  0.06218455  0.30055612  0.91737213
   0.64259349  0.46649105  0.48960352  0.90777093]


### #14 create a random vector of size 30 and find the mean value

In [13]:
v14 = np.random.random(30)
m = v14.mean()
print(v14, "\nmean: {}".format(m))

[ 0.53765896  0.70371523  0.47573803  0.77899219  0.75589075  0.7405702
  0.70899524  0.47159298  0.74957444  0.81520293  0.83602488  0.50826034
  0.2131564   0.18182732  0.69089752  0.87584702  0.39552297  0.31708719
  0.09519608  0.50753416  0.58034096  0.47991543  0.14618442  0.33289754
  0.7145508   0.44493964  0.31826084  0.11814466  0.83625536  0.40080348] 
mean: 0.5243859327674895


### #15 create a 2D array with 1 on the border and 0 inside

In [14]:
v15 = np.ones((10, 10))
v15[1:-1, 1:-1] = 0
print(v15)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### #16 how to add a border (filled with 0's) around an existing array ?

In [15]:
v16 = np.ones((5, 5))
v16 = np.pad(v16, pad_width=1, mode='constant', constant_values=0)
print(v16)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### #17 what is the result of the following expression ?

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### #18 create a 5 * 5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
v18 = np.diag(1+np.arange(4), k=-1)
print(v18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### #19 create a 8 * 8 matrix and fill it with a checkerboard pattern

In [18]:
v19 = np.zeros((8, 8))
v19[1::2, ::2] = 1
v19[::2, 1::2] = 1
print(v19)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


### #20 consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ? 

In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### #21 create a chekerboard 8 * 8 matrix using the tile function

In [20]:
v21 = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(v21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### #22 normalize a 5 * 5 random matrix

In [21]:
v22 = np.random.random((5, 5))
v_min, v_max = v22.min(), v22.max()
v22 = (v22 - v_min) / (v_max - v_min)
print(v22)

[[ 0.29247156  0.34800837  0.15961629  0.11384755  0.14702607]
 [ 1.          0.82323393  0.40042506  0.49294599  0.        ]
 [ 0.39645305  0.09428489  0.13463872  0.99848755  0.73221507]
 [ 0.7976382   0.38690482  0.68243595  0.73468248  0.09461135]
 [ 0.76959446  0.17422336  0.92467839  0.21136993  0.35307944]]


In [22]:
v22 = np.random.random((5, 5))
v_mean, v_sigma = v22.mean(), v22.std()
v22 = (v22 - v_mean) / v_sigma
print(v22)

[[ 0.11139129 -0.74965638 -0.11868759 -1.55806213  1.1231727 ]
 [-1.2200485  -1.50030239  0.43530142 -0.3947081   0.40145786]
 [ 1.3725158   0.63715176 -0.48325193 -1.03359065 -0.59692997]
 [ 0.66153482  1.12077841  1.60450666 -0.3873912  -0.22000181]
 [ 0.548648    1.29374091 -1.41069766  1.60127815 -1.23814947]]


### #23 create a custom dtype that describes a color as four unsinged bytes 

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### #24 multiply a 5 * 3 matrix by a 3 * 2 matrix (real matrix product)

In [24]:
v24 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
v24 = np.ones((5, 3)) @ np.ones((3, 2))
print(v24)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### #25 given a 1D array, negate all elements which are between 3 and 8, in place

In [25]:
v25 = np.arange(10)
v25[(3 <= v25) & (v25 <= 8)] *= -1
print(v25)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


### #26 what is the output of the following script ?

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### #27 consider an integer vector Z, which of these expressions are legal ?

In [27]:
z = np.arange(5)
print(z * z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)

[ 0  1  4  9 16]
[0 1 2 4 8]
[False False False False False]
[ 0.+0.j  0.+1.j  0.+2.j  0.+3.j  0.+4.j]
[ 0.  1.  2.  3.  4.]


### #28 what are the result of the following expressions ?

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### #29 how to round away from zero a float array ?

In [29]:
v29 = np.random.uniform(-10,10,20)
print(v29)
print(np.copysign(np.ceil(np.abs(v29)), v29))

[-4.18649034 -0.29003989 -4.8745195  -3.26242953 -0.63839554  9.52360185
  4.58855751  1.66493198 -8.253491   -4.80373973 -3.61527313  5.3057704
 -2.64799169 -0.75098882  7.21731897 -6.04336915  8.44465061 -2.2208259
  3.50516893 -8.95608875]
[ -5.  -1.  -5.  -4.  -1.  10.   5.   2.  -9.  -5.  -4.   6.  -3.  -1.   8.
  -7.   9.  -3.   4.  -9.]


### #30 how to find common values between two arrays ?

In [30]:
v30_1 = np.random.randint(-10, 10, 10)
v30_2 = np.random.randint(-10, 10, 10)
print(v30_1)
print(v30_2)
print(np.intersect1d(v30_1, v30_2))

[-8 -2  6 -5 -7 -9 -5  8  0 -3]
[-5 -5  2  9 -3  6  8 -1  3 -6]
[-5 -3  6  8]


### #31 how to ignore all numpy warnings

In [31]:
env = np.seterr(all="ignore") #無視
np.seterr(**env) #戻す

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

### #32 is the following expressions true ?

In [32]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


### #33 how to get the dates of yesterday, today and tomorrow ?

In [33]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2017-12-30
2017-12-31
2018-01-01


### #34 how to get all dates corresponding to the month of july ?

In [34]:
v34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### #35 how to compute ((A+B)*(-A/2)) in place

In [35]:
a = np.ones(3) * 1
b = np.ones(3) * 2
c = np.ones(3) * 3
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print(a)

[-1.5 -1.5 -1.5]


### #36 extract the integer part of a random array using 5 different methods

In [36]:
Z = np.random.uniform(0,10,10)

print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 0.72230738  4.50776536  2.7631827   4.3040733   7.94957106  6.45926137
  3.28916666  6.85641911  3.47483789  3.72693827]
[ 0.  4.  2.  4.  7.  6.  3.  6.  3.  3.]
[ 0.  4.  2.  4.  7.  6.  3.  6.  3.  3.]
[ 0.  4.  2.  4.  7.  6.  3.  6.  3.  3.]
[0 4 2 4 7 6 3 6 3 3]
[ 0.  4.  2.  4.  7.  6.  3.  6.  3.  3.]


### #37 create a 5 * 5 matrix with row values ranging from 0 to 4

In [37]:
v37 = np.zeros((5, 5))
v37 += np.arange(5)
print(v37)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


### #38 consider a generator function that generates 10 integers and use it to build an array

In [38]:
iterable = (x for x in range(10))
print(np.fromiter(iterable, np.int))

[0 1 2 3 4 5 6 7 8 9]


### #39 create a vector of size 10 with values ranging from 0 to 1, both excluded

In [39]:
v39 = np.linspace(0, 1, 11, endpoint=False)[1:]
print(v39)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


### #40 create a random vector of size 10 and sort it

In [40]:
v40 = np.random.random(10)
print(np.sort(v40))
print(np.sort(v40)[::-1])
print(v40)

[ 0.12034677  0.40299305  0.41174435  0.539259    0.59385907  0.59750998
  0.66968718  0.69553701  0.81666314  0.82010191]
[ 0.82010191  0.81666314  0.69553701  0.66968718  0.59750998  0.59385907
  0.539259    0.41174435  0.40299305  0.12034677]
[ 0.41174435  0.539259    0.40299305  0.81666314  0.12034677  0.66968718
  0.59385907  0.82010191  0.59750998  0.69553701]


### #41 how to sum a small array faster than np.sum ?

In [41]:
v41 = np.arange(10)
print(v41)
print(np.add.reduce(v41))
print(np.sum(v41))

[0 1 2 3 4 5 6 7 8 9]
45
45


### #42 consider two random array A and B check if they are equal

In [42]:
a = np.random.random(10)
b = np.random.random(10)
close = np.allclose(a, b)
equal = np.array_equal(a, b)
print(a)
print(b)
print(close)
print(equal)

[ 0.18891263  0.63681944  0.60804013  0.10246987  0.55080719  0.99860856
  0.51690774  0.04484662  0.69645989  0.96249778]
[ 0.96387742  0.66497425  0.46127657  0.38699894  0.41999478  0.03483502
  0.75510508  0.76044006  0.11477925  0.31759452]
False
False


### #43 make an array immutable (read-only)

In [43]:
v43 = np.random.random(10)
v43.flags.writeable = False
print(v43)
v43[1] = 1

[ 0.01680849  0.9289662   0.02567394  0.65238293  0.39444012  0.74898075
  0.37787635  0.43291065  0.68730933  0.16262797]


ValueError: assignment destination is read-only

### #44 consider a random 10 * 2 matrix representing cartesian coordinates, convert them to polar coordinates

In [ ]:
v44 = np.random.random((10, 2))
print(v44)
X, Y = v44[:, 0], v44[:, 1]
r = np.sqrt(X**2+Y**2)
theta = np.arctan2(Y, X)
print("r: {}\ntheta: {}".format(r, theta))

### #45 create random vector of size 10 and replace the maximum value by 0

In [ ]:
v45 = np.random.random(10)
print(v45)
v45[v45.argmax()] = 0
print(v45)

### #46 Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

### #47 Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

### #48 Print the minimum and maximum representable value for each numpy scalar type

In [ ]:
int_types = [np.int8, np.int32, np.int64]
float_types = [np.float32, np.float64]

for dtype in int_types:
   print("min: {}".format(np.iinfo(dtype).min))
   print("max: {}".format(np.iinfo(dtype).max))
for dtype in float_types:
   print("min: {}".format(np.finfo(dtype).min))
   print("max: {}".format(np.finfo(dtype).max))
   print("eps: {}".format(np.finfo(dtype).eps))

### #49 how to print all the values of an array ? 

In [ ]:
#np.set_printoptions(threshold=np.nan)
Z = np.random.random((16,16))
print(Z)

### #50 how to find the closest value (to a given scalar) in a vector ?

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

### #51 Create a structured array representing a position (x,y) and a color (r,g,b)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

### #52 consider a random vector with shape (100, 2) representing coordinates, find point by point distances

In [ ]:
v52 = np.random.random((100, 2))
X,Y = np.atleast_2d(v52[:,0], v52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

### #53 how to convert a float array into an integer in place ?

In [ ]:
v53 = np.arange(10, dtype=np.int32)
v53 = v53.astype(np.float32)
print(v53)

### #54 how to read the following file ?

In [ ]:
from io import StringIO
 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
#Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
#print(Z)

### #55 what is the equivalent of enumerate for numpy arrays ?

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("--------------")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

### #55 generate a generic 2D gaussian-like array

In [59]:
a = np.linspace(-1, 1, 10)
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
print("a:\n{}".format(a))
print("X:\n{}".format(X))
print("Y:\n{}".format(Y))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("G:\n{}".format(G))

a:
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
X:
[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.      

### #57 how to randomly place p elements in a 2D array ?

In [100]:
n = 10
p = 3
v57 = np.zeros((n, n))
np.put(v57, np.random.choice(range(n*n), p, replace=False), 1)
print(v57)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


### #58 substract the mean of each row of matrix

In [138]:
v58 = np.random.rand(5, 10)
print("v58:\n{}".format(v58))
v58_mean = v58.mean(axis=1, keepdims=True)
v58 -= v58_mean
print("v58_new:\n{}".format(v58))

v58:
[[ 0.37264266  0.11496856  0.02480371  0.74650926  0.43880948  0.01966626
   0.8582991   0.7777073   0.62775826  0.98643033]
 [ 0.97154141  0.97711546  0.87566907  0.97532893  0.91929462  0.20326908
   0.30561125  0.12816463  0.36968842  0.21599018]
 [ 0.02651782  0.81441621  0.63814762  0.04176891  0.187611    0.60148525
   0.26969276  0.59517161  0.16486114  0.87964685]
 [ 0.63668083  0.41523956  0.32391198  0.27048953  0.74301341  0.35092824
   0.96619169  0.27683562  0.94970174  0.25518293]
 [ 0.48750913  0.86573268  0.49924436  0.28668379  0.91056383  0.73341502
   0.75874699  0.88738315  0.97338173  0.63734832]]
v58_new:
[[-0.12411684 -0.38179093 -0.47195578  0.24974977 -0.05795001 -0.47709324
   0.3615396   0.28094781  0.13099877  0.48967084]
 [ 0.3773741   0.38294815  0.28150177  0.38116162  0.32512732 -0.39089822
  -0.28855606 -0.46600268 -0.22447888 -0.37817713]
 [-0.3954141   0.39248429  0.2162157  -0.380163   -0.23432091  0.17955333
  -0.15223916  0.17323969 -0.2570707

### #59 how to i sort an array by the nth column ?

In [167]:
v59 = np.random.rand(5, 5)
print("before:\n{}".format(v59))
print("after:\n{}".format(v59[v59[:,1].argsort()]))

before:
[[ 0.8970022   0.07514485  0.57674863  0.93119525  0.92557705]
 [ 0.53860165  0.96608098  0.42040336  0.20682414  0.75586909]
 [ 0.41384678  0.06475181  0.91036738  0.55815191  0.32463748]
 [ 0.75620228  0.72056548  0.60131563  0.35775672  0.38549831]
 [ 0.80863533  0.53776179  0.0911316   0.1344051   0.48454792]]
after:
[[ 0.41384678  0.06475181  0.91036738  0.55815191  0.32463748]
 [ 0.8970022   0.07514485  0.57674863  0.93119525  0.92557705]
 [ 0.80863533  0.53776179  0.0911316   0.1344051   0.48454792]
 [ 0.75620228  0.72056548  0.60131563  0.35775672  0.38549831]
 [ 0.53860165  0.96608098  0.42040336  0.20682414  0.75586909]]


### #60 how to tell if a given 2D array has null columns ?

In [299]:
v60 = np.random.randint(0, 3, (3, 3))
print("v60:\n{}".format(v60))
print((~v60.any(axis=0)).any())

v60:
[[2 0 2]
 [1 0 1]
 [1 0 2]]
True


### #61 find the nearest value from a given value in an array ?

In [303]:
v61 = np.random.uniform(0,1,10)
num = 0.5
val = v61.flat[np.abs(v61 - num).argmin()]
print(v61)
print(val)

[ 0.69255258  0.64077701  0.00511744  0.11889895  0.46138216  0.37446515
  0.90256359  0.30384022  0.53665998  0.01556231]
0.536659984434


### #62 considering two arrays with shape (1,3) and (3,1 ), how to compute their sum using an iterator ?

In [308]:
a = np.arange(3).reshape(1, 3)
b = np.arange(3).reshape(3, 1)
print("a:\n{}".format(a))
print("b:\n{}".format(b))
it = np.nditer([a,b,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

a:
[[0 1 2]]
b:
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


### #63 create an array class that has a same attribute

In [315]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


### #64 consider a given vector, how to add 1 to each element indexed by a second vector 

In [325]:
a = np.ones(10)
b = np.random.randint(0,10,5)
print(a)
print(b)
np.add.at(a,b,1)
print(a)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[9 8 0 2 9]
[ 2.  1.  2.  1.  1.  1.  1.  1.  2.  3.]


### #65 how to accumulate elements of a vector (X) to an array (F) based on an index list (I) ?

In [327]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[ 0.  7.  0.  6.  5.  0.  0.  0.  0.  3.]


### #66 Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [329]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


### #67 considering a four dimensions array, how to get sum over the last two axis at once ?

In [333]:
print("67:")
A = np.random.randint(0,5,(3,4,3,4))
print(A)
B = A.sum(axis=(-1,-2))
print(B)

67:
[[[[4 3 4 2]
   [2 3 1 3]
   [3 1 4 2]]

  [[1 2 2 4]
   [4 2 1 3]
   [1 4 0 2]]

  [[1 2 3 2]
   [3 0 2 0]
   [3 4 3 1]]

  [[4 4 2 0]
   [1 3 1 1]
   [2 2 4 1]]]


 [[[1 3 2 0]
   [1 0 3 4]
   [4 0 3 2]]

  [[0 2 3 3]
   [1 2 0 3]
   [1 0 0 4]]

  [[3 4 1 4]
   [1 2 4 4]
   [3 1 3 0]]

  [[4 1 0 3]
   [1 3 2 3]
   [4 4 2 4]]]


 [[[4 2 4 2]
   [1 0 4 0]
   [3 3 4 2]]

  [[3 4 2 2]
   [2 0 0 4]
   [1 2 4 1]]

  [[3 4 2 1]
   [2 0 1 3]
   [3 2 0 4]]

  [[4 4 2 1]
   [1 2 0 1]
   [3 0 4 0]]]]
[[32 26 24 25]
 [23 19 30 31]
 [29 25 25 22]]


### #68 considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices ?

In [338]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
import pandas as pd
print(D)
print(S)
print(pd.Series(D).groupby(S).mean())

[ 0.11329981  0.13713545  0.99568261  0.39537813  0.49905292  0.62627051
  0.37909792  0.44404426  0.19322901  0.99829218  0.97082215  0.23678102
  0.09172192  0.68642511  0.70749698  0.68393424  0.90180752  0.61335331
  0.86416292  0.13479966  0.62711325  0.44865741  0.41466404  0.87599677
  0.78644237  0.49936067  0.1460894   0.73216279  0.20652422  0.65254863
  0.76866124  0.34592479  0.76297318  0.9955919   0.85330918  0.48007275
  0.151643    0.28050324  0.18574172  0.79535422  0.56462846  0.36068992
  0.62112728  0.89905989  0.50934006  0.97543358  0.82458149  0.5102635
  0.35348749  0.83113272  0.42686669  0.19316474  0.02451759  0.25361784
  0.61905686  0.03497789  0.34161384  0.59688833  0.30609343  0.66724573
  0.81199813  0.02958657  0.74394092  0.53233904  0.99793369  0.35848458
  0.90247053  0.99954544  0.85713581  0.76517158  0.04348547  0.26987174
  0.11216133  0.26209289  0.03469535  0.83364488  0.03161536  0.57099162
  0.43997162  0.90278931  0.73121055  0.07896613  0.

### #69 how to get the diagonal of a dot product ?

In [346]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A, B)))
print(np.sum(A * B.T, axis=1))

[ 0.68193518  0.89694426  1.15309839  0.99859267  2.14881217]
[ 0.68193518  0.89694426  1.15309839  0.99859267  2.14881217]


### #70 consider the vector [1,2,3,4,5], how to build a new vector with 3 consecutive zeros interleaved between each value ?

In [352]:
a = np.array([1,2,3,4,5])
nz = 3
a0 = np.zeros((len(a)-1)*nz+len(a))
a0[::nz+1] = a
print(a0)

[ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]


### #71 consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5) ?

In [355]:
A = np.random.random((5,5,3))
B = np.arange(25).reshape((5,5))
print("A:\n{}".format(A))
print("B:\n{}".format(B))
print(A * B[:,:,None])

A:
[[[ 0.51749296  0.09128034  0.89085769]
  [ 0.28525187  0.47037326  0.30095411]
  [ 0.08196687  0.61796465  0.14080734]
  [ 0.57702089  0.66258102  0.40717728]
  [ 0.37466719  0.78125779  0.88746587]]

 [[ 0.02359015  0.17095349  0.68111313]
  [ 0.01534764  0.7150822   0.08869362]
  [ 0.7192879   0.50744929  0.91170764]
  [ 0.60586091  0.70710674  0.3844004 ]
  [ 0.13138554  0.32139747  0.90988684]]

 [[ 0.0779346   0.14490894  0.98588472]
  [ 0.43132875  0.79341676  0.48650674]
  [ 0.73967298  0.891824    0.21898668]
  [ 0.53236259  0.97003655  0.80611675]
  [ 0.55545328  0.31332095  0.14630716]]

 [[ 0.39575869  0.35900248  0.67908764]
  [ 0.15512507  0.97275257  0.31386087]
  [ 0.42966107  0.21534219  0.10114453]
  [ 0.92143696  0.94728094  0.72416071]
  [ 0.5950614   0.2134986   0.88413319]]

 [[ 0.18828193  0.55475751  0.10689187]
  [ 0.87836562  0.99716459  0.53708483]
  [ 0.56260471  0.44444484  0.66516062]
  [ 0.66115623  0.43757848  0.90773104]
  [ 0.64150813  0.04676451  0

### #72 how to swap two rows of an array ?

In [363]:
v72 = np.arange(20).reshape(5,4)
print(v72)
v72[[0,1]] = v72[[1, 0]]
print("swap:\n{}".format(v72))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
swap:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
