### #1 import the numpy package under the name np

In [1]:
import numpy as np

### #2 print the numpy version and configuration

In [2]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/owner/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\

### #3 create null vector of size 10

In [3]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### #4 how to find the memory size of any array

In [4]:
v.itemsize * v.size

80

### #6 create a null vector of size 10 but the fifth value which is 1

In [5]:
v5 = np.zeros(10)
v5[4] = 1
print(v5)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### #7 create a vector with values ranging from 10 to 49 

In [6]:
v7 = np.arange(10, 50)
print(v7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### #8 reverse a vector

In [7]:
v8 = v7[::-1]
print(v8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### #9 create a 3*3 matirix with values ranging from 0 to 8

In [8]:
v9 = np.arange(0, 9).reshape(3, 3)
v9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### #10 find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
v10 = np.nonzero([1, 2, 0, 0, 4, 0])
print(v10)

(array([0, 1, 4], dtype=int64),)


### #11 create a 3*3 identity matrix

In [10]:
v11 = np.eye(3)
print(v11)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### #12 create a 3*3*3 array with random values

In [11]:
v12 = np.random.random((3, 3, 3))
print(v12)

[[[ 0.74743253  0.06404697  0.69520166]
  [ 0.48664612  0.20232187  0.13617779]
  [ 0.08881147  0.38256213  0.82705878]]

 [[ 0.89170754  0.69482498  0.93144612]
  [ 0.26849431  0.15204249  0.87595151]
  [ 0.15032404  0.9840022   0.94718617]]

 [[ 0.04456045  0.20806234  0.66518604]
  [ 0.34412417  0.61124101  0.40741174]
  [ 0.16179505  0.33489983  0.95204796]]]


### #13 create a 10*10 array with random values and find the minimum and maximum values

In [12]:
v13 = np.random.random((10, 10))
v_min, v_max = v13.min(), v13.max()
print(v13)
print("minimum: {}\nmaximum: {}".format(v_min, v_max))

[[ 0.55683747  0.94215071  0.99697988  0.10711295  0.33222067  0.81028842
   0.35613398  0.41281003  0.93344705  0.93813565]
 [ 0.09010089  0.43358095  0.79316501  0.80897614  0.24824938  0.41301612
   0.63140331  0.7107687   0.59133321  0.37465246]
 [ 0.15654017  0.30846199  0.33122805  0.97907062  0.08419835  0.14385139
   0.7842191   0.90434849  0.73259347  0.70351006]
 [ 0.09643087  0.983668    0.09714175  0.89137035  0.07202218  0.11864433
   0.12405562  0.26464211  0.69838166  0.23844917]
 [ 0.07253958  0.18520763  0.8764436   0.5092842   0.12730457  0.25460287
   0.77541703  0.41869166  0.14126389  0.37731931]
 [ 0.20900727  0.47168959  0.86160278  0.27386584  0.22449663  0.46002169
   0.69708062  0.4309518   0.00880661  0.87949601]
 [ 0.1313034   0.66872775  0.77790777  0.25631366  0.57140983  0.24320742
   0.30053435  0.01961749  0.12410272  0.61073169]
 [ 0.42094387  0.34030189  0.18430764  0.54413459  0.60166259  0.33738066
   0.62424399  0.11726769  0.8469763   0.37180443]


### #14 create a random vector of size 30 and find the mean value

In [13]:
v14 = np.random.random(30)
m = v14.mean()
print(v14, "\nmean: {}".format(m))

[ 0.36807973  0.67827938  0.27808959  0.09472202  0.8711323   0.15452811
  0.07585517  0.26565864  0.95821521  0.38321254  0.38392972  0.12506376
  0.11308392  0.47841247  0.92350817  0.26406448  0.75938035  0.04375532
  0.75665374  0.04461661  0.18574017  0.81623199  0.00492927  0.99171904
  0.53955899  0.42694958  0.70688352  0.43765956  0.46453735  0.5605264 ] 
mean: 0.4384992366934359


### #15 create a 2D array with 1 on the border and 0 inside

In [14]:
v15 = np.ones((10, 10))
v15[1:-1, 1:-1] = 0
print(v15)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### #16 how to add a border (filled with 0's) around an existing array ?

In [15]:
v16 = np.ones((5, 5))
v16 = np.pad(v16, pad_width=1, mode='constant', constant_values=0)
print(v16)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### #17 what is the result of the following expression ?

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### #18 create a 5 * 5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
v18 = np.diag(1+np.arange(4), k=-1)
print(v18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### #19 create a 8 * 8 matrix and fill it with a checkerboard pattern

In [18]:
v19 = np.zeros((8, 8))
v19[1::2, ::2] = 1
v19[::2, 1::2] = 1
print(v19)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


### #20 consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ? 

In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### #21 create a chekerboard 8 * 8 matrix using the tile function

In [20]:
v21 = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(v21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### #22 normalize a 5 * 5 random matrix

In [21]:
v22 = np.random.random((5, 5))
v_min, v_max = v22.min(), v22.max()
v22 = (v22 - v_min) / (v_max - v_min)
print(v22)

[[ 0.54607516  0.5677405   0.7091416   0.95901216  1.        ]
 [ 0.55379101  0.57140864  0.17063931  0.38441028  0.36204941]
 [ 0.16491072  0.19686964  0.65189234  0.7219489   0.        ]
 [ 0.82479379  0.73170924  0.50771408  0.07378859  0.00167389]
 [ 0.50661154  0.03353994  0.82376641  0.27012976  0.73201028]]


In [22]:
v22 = np.random.random((5, 5))
v_mean, v_sigma = v22.mean(), v22.std()
v22 = (v22 - v_mean) / v_sigma
print(v22)

[[ 0.25941995  0.20994851  0.56885133  1.20815548 -0.95358787]
 [-1.31154646 -1.48666742 -1.60081161 -1.31629381  0.02647437]
 [-0.18111343  1.34448175 -0.82996794  1.27909952 -0.02409595]
 [ 0.94476002 -0.40283616  0.70078483  1.61520254  1.61171585]
 [-0.98842413  0.87860256 -0.80005499  0.05958351 -0.81168045]]


### #23 create a custom dtype that describes a color as four unsinged bytes 

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### #24 multiply a 5 * 3 matrix by a 3 * 2 matrix (real matrix product)

In [24]:
v24 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
v24 = np.ones((5, 3)) @ np.ones((3, 2))
print(v24)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### #25 given a 1D array, negate all elements which are between 3 and 8, in place

In [25]:
v25 = np.arange(10)
v25[(3 <= v25) & (v25 <= 8)] *= -1
print(v25)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


### #26 what is the output of the following script ?

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


### #27 consider an integer vector Z, which of these expressions are legal ?

In [27]:
z = np.arange(5)
print(z * z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)

[ 0  1  4  9 16]
[0 1 2 4 8]
[False False False False False]
[ 0.+0.j  0.+1.j  0.+2.j  0.+3.j  0.+4.j]
[ 0.  1.  2.  3.  4.]


### #28 what are the result of the following expressions ?

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### #29 how to round away from zero a float array ?

In [29]:
v29 = np.random.uniform(-10,10,20)
print(v29)
print(np.copysign(np.ceil(np.abs(v29)), v29))

[ 7.28124953 -3.37250856  3.09039162 -8.60241282  6.60742309 -2.60414407
 -5.08007091 -5.51982532 -3.45871037 -2.68416663 -2.70443118  1.65324105
 -3.46405651 -9.6240809   7.95501127  6.74047008  6.38799099 -2.11682666
  0.36940498 -3.87169209]
[  8.  -4.   4.  -9.   7.  -3.  -6.  -6.  -4.  -3.  -3.   2.  -4. -10.   8.
   7.   7.  -3.   1.  -4.]


### #30 how to find common values between two arrays ?

In [31]:
v30_1 = np.random.randint(-10, 10, 10)
v30_2 = np.random.randint(-10, 10, 10)
print(v30_1)
print(v30_2)
print(np.intersect1d(v30_1, v30_2))

[-5  4 -2 -9  2  2 -6  2  9  1]
[ 1  7  6  5 -3  8 -6 -7 -9 -1]
[-9 -6  1]


### #31 how to ignore all numpy warnings

In [33]:
env = np.seterr(all="ignore") #無視
np.seterr(**env) #戻す

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

### #32 is the following expressions true ?

In [37]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


### #33 how to get the dates of yesterday, today and tomorrow ?

In [49]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2017-12-29
2017-12-30
2017-12-31


### #34 how to get all dates corresponding to the month of july ?

In [54]:
v34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


### #35 how to compute ((A+B)*(-A/2)) in place

In [75]:
a = np.ones(3) * 1
b = np.ones(3) * 2
c = np.ones(3) * 3
np.add(a, b, out=b)
np.divide(a, 2, out=a)
np.negative(a, out=a)
np.multiply(a, b, out=a)
print(a)

[-1.5 -1.5 -1.5]


### #36 extract the integer part of a random array using 5 different methods

In [78]:
Z = np.random.uniform(0,10,10)

print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[ 7.15875733  1.00524863  4.77145008  2.06356986  5.18277723  1.02966325
  3.2515194   1.74333603  0.33961564  6.68545548]
[ 7.  1.  4.  2.  5.  1.  3.  1.  0.  6.]
[ 7.  1.  4.  2.  5.  1.  3.  1.  0.  6.]
[ 7.  1.  4.  2.  5.  1.  3.  1.  0.  6.]
[7 1 4 2 5 1 3 1 0 6]
[ 7.  1.  4.  2.  5.  1.  3.  1.  0.  6.]


### #37 create a 5 * 5 matrix with row values ranging from 0 to 4

In [83]:
v37 = np.zeros((5, 5))
v37 += np.arange(5)
print(v37)

[[ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]
 [ 0.  1.  2.  3.  4.]]


### #38 consider a generator function that generates 10 integers and use it to build an array

In [97]:
iterable = (x for x in range(10))
print(np.fromiter(iterable, np.int))

[0 1 2 3 4 5 6 7 8 9]


### #39 create a vector of size 10 with values ranging from 0 to 1, both excluded

In [151]:
v39 = np.linspace(0, 1, 11, endpoint=False)[1:]
print(v39)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


### #40 create a random vector of size 10 and sort it

In [200]:
v40 = np.random.random(10)
print(np.sort(v40))
print(np.sort(v40)[::-1])
print(v40)

[ 0.10387509  0.13386174  0.16110261  0.16534791  0.18781113  0.18842093
  0.38296615  0.47863921  0.66377541  0.79330818]
[ 0.79330818  0.66377541  0.47863921  0.38296615  0.18842093  0.18781113
  0.16534791  0.16110261  0.13386174  0.10387509]
[ 0.66377541  0.13386174  0.16110261  0.79330818  0.10387509  0.18842093
  0.47863921  0.16534791  0.38296615  0.18781113]


### #41 how to sum a small array faster than np.sum ?

In [206]:
v41 = np.arange(10)
print(v41)
print(np.add.reduce(v41))
print(np.sum(v41))

[0 1 2 3 4 5 6 7 8 9]
45
45


### #42 consider two random array A and B check if they are equal

In [217]:
a = np.random.random(10)
b = np.random.random(10)
close = np.allclose(a, b)
equal = np.array_equal(a, b)
print(a)
print(b)
print(close)
print(equal)

[ 0.44639437  0.76464111  0.56569034  0.30760015  0.06954211  0.15068022
  0.28721961  0.09468248  0.19008832  0.35233477]
[ 0.21824686  0.98525907  0.07724513  0.32617423  0.04367223  0.22511945
  0.21414013  0.17365327  0.82818359  0.17287426]
False
False


### #43 make an array immutable (read-only)

In [226]:
v43 = np.random.random(10)
v43.flags.writeable = False
print(v43)
v43[1] = 1

[ 0.30540529  0.63879123  0.64227089  0.64398053  0.76342544  0.52120778
  0.01703807  0.79392857  0.74621529  0.22678601]


ValueError: assignment destination is read-only

### #44 consider a random 10 * 2 matrix representing cartesian coordinates, convert them to polar coordinates

In [239]:
v44 = np.random.random((10, 2))
print(v44)
X, Y = v44[:, 0], v44[:, 1]
r = np.sqrt(X**2+Y**2)
theta = np.arctan2(Y, X)
print("r: {}\ntheta: {}".format(r, theta))

[[ 0.13882828  0.06556096]
 [ 0.33759736  0.23682661]
 [ 0.61459529  0.11032266]
 [ 0.90635294  0.23054292]
 [ 0.4984366   0.79411197]
 [ 0.65044662  0.8348791 ]
 [ 0.92253726  0.79146974]
 [ 0.10673042  0.68542335]
 [ 0.37345334  0.21171811]
 [ 0.15964226  0.83098876]]
r: [ 0.15353023  0.41238189  0.62441849  0.93521425  0.93757819  1.05834962
  1.21552431  0.69368332  0.42929239  0.84618436]
theta: [ 0.4411981   0.61173606  0.177613    0.24908106  1.01028262  0.90893557
  0.70907821  1.41632227  0.51574063  1.38099752]


### #45 create random vector of size 10 and replace the maximum value by 0

In [245]:
v45 = np.random.random(10)
print(v45)
v45[v45.argmax()] = 0
print(v45)

[ 0.33814941  0.34220071  0.60387578  0.31668466  0.04423568  0.32237918
  0.32201721  0.71010841  0.75760156  0.02143092]
[ 0.33814941  0.34220071  0.60387578  0.31668466  0.04423568  0.32237918
  0.32201721  0.71010841  0.          0.02143092]


### #46 Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 

In [247]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[( 0.  ,  0.  ) ( 0.25,  0.  ) ( 0.5 ,  0.  ) ( 0.75,  0.  )
  ( 1.  ,  0.  )]
 [( 0.  ,  0.25) ( 0.25,  0.25) ( 0.5 ,  0.25) ( 0.75,  0.25)
  ( 1.  ,  0.25)]
 [( 0.  ,  0.5 ) ( 0.25,  0.5 ) ( 0.5 ,  0.5 ) ( 0.75,  0.5 )
  ( 1.  ,  0.5 )]
 [( 0.  ,  0.75) ( 0.25,  0.75) ( 0.5 ,  0.75) ( 0.75,  0.75)
  ( 1.  ,  0.75)]
 [( 0.  ,  1.  ) ( 0.25,  1.  ) ( 0.5 ,  1.  ) ( 0.75,  1.  )
  ( 1.  ,  1.  )]]


### #47 Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [248]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.16363712


### #48 Print the minimum and maximum representable value for each numpy scalar type

In [254]:
int_types = [np.int8, np.int32, np.int64]
float_types = [np.float32, np.float64]

for dtype in int_types:
   print("min: {}".format(np.iinfo(dtype).min))
   print("max: {}".format(np.iinfo(dtype).max))
for dtype in float_types:
   print("min: {}".format(np.finfo(dtype).min))
   print("max: {}".format(np.finfo(dtype).max))
   print("eps: {}".format(np.finfo(dtype).eps))

min: -128
max: 127
min: -2147483648
max: 2147483647
min: -9223372036854775808
max: 9223372036854775807
min: -3.4028234663852886e+38
max: 3.4028234663852886e+38
eps: 1.1920928955078125e-07
min: -1.7976931348623157e+308
max: 1.7976931348623157e+308
eps: 2.220446049250313e-16


### #49 how to print all the values of an array ? 

In [301]:
#np.set_printoptions(threshold=np.nan)
Z = np.random.random((16,16))
print(Z)

[[  4.50001117e-02   2.55449177e-02   2.42332950e-01   6.87005059e-01
    9.31859547e-01   1.60941278e-01   2.34824012e-01   3.14518996e-01
    2.93547950e-01   3.97759774e-01   3.73320300e-01   6.41337215e-01
    6.05143348e-01   9.78375528e-01   7.48762866e-01   3.19422084e-01]
 [  1.77969967e-01   1.94194642e-01   5.83732715e-01   9.84311129e-01
    6.74585421e-02   1.41650820e-01   4.71671321e-01   9.45580722e-02
    1.81175498e-01   6.64392898e-01   5.73037443e-01   9.85785467e-02
    3.40838753e-01   6.44626774e-01   3.23013645e-01   4.37605033e-01]
 [  7.56193059e-01   7.34700632e-01   6.43895463e-01   5.87441587e-01
    2.67784795e-01   5.87728825e-01   6.93706607e-01   5.51070642e-01
    2.31368485e-01   7.06509880e-02   9.32846169e-01   1.70079669e-01
    8.99984475e-01   5.16616995e-01   6.43148225e-01   9.24821077e-01]
 [  7.33078811e-01   8.09707621e-01   9.27845841e-02   9.21759920e-01
    5.84179582e-01   5.68420520e-01   6.35095722e-01   8.90447368e-01
    2.09816723e-0

### #50 how to find the closest value (to a given scalar) in a vector ?

In [305]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z)
print(v)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
13.10132585276107
13


### #51 Create a structured array representing a position (x,y) and a color (r,g,b)

In [307]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[(( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))
 (( 0.,  0.), ( 0.,  0.,  0.)) (( 0.,  0.), ( 0.,  0.,  0.))]


### #52 consider a random vector with shape (100, 2) representing coordinates, find point by point distances

In [313]:
v52 = np.random.random((100, 2))
X,Y = np.atleast_2d(v52[:,0], v52[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[ 0.          0.68312024  0.3258008   0.11826511  0.14784036  0.59269031
   0.05623626  0.46004126  0.25250753  0.47800592  0.28347457  0.41732324
   0.86601711  0.74101808  0.24682575  0.2994089   0.50433954  0.53613791
   0.18334374  0.46568127  0.91370227  0.65489575  0.20673711  0.39468966
   0.86976264  0.72080093  0.87176796  0.84825768  0.66402159  0.19772973
   0.43041301  0.8483785   0.10627666  0.54033761  0.87433187  0.29352334
   0.84060772  0.42912471  0.70862967  0.56591481  0.58958932  0.45156718
   0.72442818  0.38082559  0.57229861  0.35562333  0.41164877  0.8579575
   0.74918198  0.92834646  0.44318064  0.48978012  0.52260048  0.704132
   0.37703748  0.92600485  0.57978961  0.71276792  0.14805785  0.60516795
   0.22544544  0.44841898  0.09947285  0.88307955  0.9096053   0.93060372
   0.37654078  0.72622411  0.61112201  0.63435636  0.91935319  0.31453047
   0.66256946  0.42651132  0.6547035   0.17456572  0.87476474  0.85977725
   0.43071635  0.92238901  0.38236178  0.

[[ 0.          0.45659626  0.63056061  0.67057956  0.4215558   0.7151715
   0.32891332  0.85715961  0.69052138  0.09744453]
 [ 0.45659626  0.          0.46546668  0.32425003  0.08060352  0.37451759
   0.27762756  0.78404297  0.58481379  0.45171184]
 [ 0.63056061  0.46546668  0.          0.2514821   0.3951245   0.82078073
   0.68286471  0.32056856  0.12536423  0.6953399 ]
 [ 0.67057956  0.32425003  0.2514821   0.          0.28941337  0.6180905
   0.595274    0.54826936  0.37089159  0.70436392]
 [ 0.4215558   0.08060352  0.3951245   0.28941337  0.          0.45508042
   0.30870221  0.71074049  0.51127078  0.43347129]
 [ 0.7151715   0.37451759  0.82078073  0.6180905   0.45508042  0.
   0.39481034  1.14109562  0.94478705  0.66195931]
 [ 0.32891332  0.27762756  0.68286471  0.595274    0.30870221  0.39481034
   0.          0.98124195  0.78584084  0.26737784]
 [ 0.85715961  0.78404297  0.32056856  0.54826936  0.71074049  1.14109562
   0.98124195  0.          0.19947053  0.93968221]
 [ 0.69052

### #53 how to convert a float array into an integer in place ?

In [326]:
v53 = np.arange(10, dtype=np.int32)
v53 = v53.astype(np.float32)
print(v53)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


### #54 how to read the following file ?

In [331]:
from io import StringIO
 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
#Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
#print(Z)

### #55 what is the equivalent of enumerate for numpy arrays ?

In [335]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
print("--------------")
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
--------------
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


### #55