### #1 import the numpy package under the name np

In [1]:
import numpy as np

### #2 print the numpy version and configuration

In [2]:
print(np.__version__)
np.show_config()

1.13.3
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/Users/owner/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/owner/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\

### #3 create null vector of size 10

In [3]:
v = np.zeros(10)
print(v)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


### #4 how to find the memory size of any array

In [4]:
v.itemsize * v.size

80

### #6 create a null vector of size 10 but the fifth value which is 1

In [5]:
v5 = np.zeros(10)
v5[4] = 1
print(v5)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


### #7 create a vector with values ranging from 10 to 49 

In [6]:
v7 = np.arange(10, 50)
print(v7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### #8 reverse a vector

In [7]:
v8 = v7[::-1]
print(v8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


### #9 create a 3*3 matirix with values ranging from 0 to 8

In [8]:
v9 = np.arange(0, 9).reshape(3, 3)
v9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### #10 find indices of non-zero elements from [1,2,0,0,4,0]

In [9]:
v10 = np.nonzero([1, 2, 0, 0, 4, 0])
print(v10)

(array([0, 1, 4], dtype=int64),)


### #11 create a 3*3 identity matrix

In [10]:
v11 = np.eye(3)
print(v11)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### #12 create a 3*3*3 array with random values

In [11]:
v12 = np.random.random((3, 3, 3))
print(v12)

[[[ 0.51319799  0.23071348  0.64703115]
  [ 0.74947517  0.16962039  0.58494193]
  [ 0.12176164  0.0484661   0.20225101]]

 [[ 0.21365362  0.88026005  0.31913956]
  [ 0.74229095  0.97766129  0.82718628]
  [ 0.37407814  0.51095343  0.93513285]]

 [[ 0.58061209  0.72515017  0.27424626]
  [ 0.54188432  0.17625761  0.43252692]
  [ 0.84736439  0.35810178  0.09812821]]]


### #13 create a 10*10 array with random values and find the minimum and maximum values

In [12]:
v13 = np.random.random((10, 10))
v_min, v_max = v13.min(), v13.max()
print(v13)
print("minimum: {}\nmaximum: {}".format(v_min, v_max))

[[ 0.01540647  0.73527088  0.15611214  0.00472217  0.33499414  0.33177549
   0.18058222  0.05329498  0.92197813  0.36522286]
 [ 0.46723411  0.12905918  0.11208813  0.83482002  0.80727276  0.52960588
   0.62803025  0.45469853  0.62839935  0.33550046]
 [ 0.02296605  0.2038558   0.31685333  0.87885095  0.65497646  0.80730307
   0.38184371  0.172371    0.87448813  0.24219986]
 [ 0.2993714   0.75872439  0.1054466   0.5172897   0.13112247  0.30017436
   0.86765873  0.96928318  0.21266932  0.46692666]
 [ 0.67856473  0.92620909  0.4810533   0.78725599  0.79836839  0.799523
   0.69092017  0.21342975  0.30945874  0.23002843]
 [ 0.82941796  0.909812    0.30953672  0.47695665  0.84758408  0.29359789
   0.49341365  0.76503342  0.29503244  0.01027164]
 [ 0.57071244  0.67221768  0.62423969  0.3329673   0.43918831  0.86285656
   0.33875797  0.31405144  0.22616159  0.12192771]
 [ 0.64310067  0.9598663   0.21369746  0.08625776  0.99549466  0.00842599
   0.21128041  0.11276259  0.62744173  0.22886343]
 [

### #14 create a random vector of size 30 and find the mean value

In [13]:
v14 = np.random.random(30)
m = v14.mean()
print(v14, "\nmean: {}".format(m))

[ 0.09004539  0.91803713  0.23243688  0.29844118  0.7772613   0.27223607
  0.38397078  0.31888756  0.48448329  0.22186712  0.80702863  0.87452245
  0.69363772  0.4288139   0.00909091  0.22134984  0.45042422  0.76261681
  0.10984741  0.86875404  0.55553611  0.44853376  0.65897794  0.68558956
  0.17537874  0.11000667  0.84707899  0.62535393  0.66144131  0.93646693] 
mean: 0.4976038859014035


### #15 create a 2D array with 1 on the border and 0 inside

In [14]:
v15 = np.ones((10, 10))
v15[1:-1, 1:-1] = 0
print(v15)

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


### #16 how to add a border (filled with 0's) around an existing array ?

In [15]:
v16 = np.ones((5, 5))
v16 = np.pad(v16, pad_width=1, mode='constant', constant_values=0)
print(v16)

[[ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


### #17 what is the result of the following expression ?

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


### #18 create a 5 * 5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
v18 = np.diag(1+np.arange(4), k=-1)
print(v18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### #19 create a 8 * 8 matrix and fill it with a checkerboard pattern

In [18]:
v19 = np.zeros((8, 8))
v19[1::2, ::2] = 1
v19[::2, 1::2] = 1
print(v19)

[[ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]
 [ 0.  1.  0.  1.  0.  1.  0.  1.]
 [ 1.  0.  1.  0.  1.  0.  1.  0.]]


### #20 consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element ? 

In [19]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


### #21 create a chekerboard 8 * 8 matrix using the tile function

In [20]:
v21 = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
print(v21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### #22 normalize a 5 * 5 random matrix

In [21]:
v22 = np.random.random((5, 5))
v_min, v_max = v22.min(), v22.max()
v22 = (v22 - v_min) / (v_max - v_min)
print(v22)

[[ 0.98415557  0.3844447   0.06428127  0.79051182  0.74413557]
 [ 0.42232702  0.24903352  0.42904293  0.70103146  0.28364204]
 [ 1.          0.          0.21980037  0.27420383  0.74734694]
 [ 0.00934142  0.897418    0.3732932   0.02989746  0.24375095]
 [ 0.99766861  0.73004491  0.86916537  0.83900645  0.63064568]]


In [22]:
v22 = np.random.random((5, 5))
v_mean, v_sigma = v22.mean(), v22.std()
v22 = (v22 - v_mean) / v_sigma
print(v22)

[[ 1.09374907 -1.40031343 -1.12463483  1.46317898 -0.9192132 ]
 [ 1.07454183  0.67501063 -1.77344589 -1.53349226 -0.78780939]
 [ 1.15509325  0.45315149  0.78656371  1.48182538 -0.62826911]
 [ 0.78476038 -0.41469626 -0.61124596  0.48322191  0.78611457]
 [-0.3522472   0.14264326 -0.27894224 -1.44530917  0.88976451]]


### #23 create a custom dtype that describes a color as four unsinged bytes 

In [23]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


### #24 multiply a 5 * 3 matrix by a 3 * 2 matrix (real matrix product)

In [24]:
v24 = np.dot(np.ones((5, 3)), np.ones((3, 2)))
v24 = np.ones((5, 3)) @ np.ones((3, 2))
print(v24)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


### #25 given a 1D array, negate all elements which are between 3 and 8, in place

In [26]:
v25 = np.arange(10)
v25[(3 <= v25) & (v25 <= 8)] *= -1
print(v25)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


### #26 what is the output of the following script ?

In [33]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


### #27 consider an integer vector Z, which of these expressions are legal ?

In [40]:
z = np.arange(5)
print(z * z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)

[ 0  1  4  9 16]
[0 1 2 4 8]
[False False False False False]
[ 0.+0.j  0.+1.j  0.+2.j  0.+3.j  0.+4.j]
[ 0.  1.  2.  3.  4.]


### #28 what are the result of the following expressions ?

In [52]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[ -2.14748365e+09]


C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\owner\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


### #29 how to round away from zero a float array ?

In [66]:
v29 = np.random.uniform(-10,10,20)
print(v29)
print(np.copysign(np.ceil(np.abs(v29)), v29))

[ 3.23185939  8.11861897 -5.10273677  0.26109532  0.72715072 -7.30648573
  4.82695885  9.94904255 -2.74151668 -4.40765335  7.81691246 -7.21833717
 -7.97490531 -2.49385887 -2.98722964 -8.05595391  1.57364347 -1.41893392
 -8.1667964  -9.91489712]
[  4.   9.  -6.   1.   1.  -8.   5.  10.  -3.  -5.   8.  -8.  -8.  -3.  -3.
  -9.   2.  -2.  -9. -10.]


### #30 how to find common values between two arrays ?

In [68]:
v30_1 = np.random.randint(-10, 10, 10)
v30_2 = np.random.randint(-10, 10, 10)
print(v30_1)
print(v30_2)

[-5  9  6 -4 -8  9 -8  8 -5  3]
[  9   0  -8  -6   6 -10  -5  -9  -1  -1]
